### ISSUE TITLE
option with cors

### ISSUE THREAD

**Issue by rushcat** [temrdm/gulp-rest-emulator#1]
Hi

I have a situation that I need to use gulp-connect and gulp-rest-emulator in the same time for test.
but there is a CORS problem.
maybe there can be a option that can use the cors module

var cors = require('cors')
function gulpRestEmulator(options) {
    var app = express();
    var config = [];
    app.use(cors())
    ---

Best
rushcat

**Comment by temrdm** [comment]
Added support for CORS. Usage:
```
options = {
    corsEnable: true,
    corsOptions: {}
}
```

**Comment by rushcat** [comment]
Thanks for replying so quickly!!!
