### ISSUE TITLE
Latency Emulation.

### ISSUE THREAD

**Issue by singerxt** [temrdm/gulp-rest-emulator#2]
Hello !

Thanks for all your hard of on gulp-rest-emulator. I think this is really cool tool. 
Did you think to add feature - Lag emulation ? ;-)

**Comment by temrdm** [comment]
It is now possible to specify a "timeout" for response in ms.
```
module.exports = {
    '/api/users': {
        data: [
            { name: 'John' },
            { name: 'Adam' }
        ],
        timeout: 2000
    }
};
```
Is that what you mean?

**Comment by singerxt** [comment]
Yes thanks!
